BanSach/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanSach.Models;

namespace BanSach.Controllers
{
    public class CustomersController : Controller
    {
        private BanSachEntities db = new BanSachEntities();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDCus,NameCus,PhoneCus,EmailCus")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDCus,NameCus,PhoneCus,EmailCus")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Tạo view cho khách hàng Login
        public ActionResult LoginCus()
        {
            return View();
        }
        // Xử lý tìm kiếm UserName, password trong Customer và thông báo
        [HttpPost]
        public ActionResult LoginAcountCus(Customer _cus)
        {
            // check là khách hàng cần tìm
            var check = db.Customers.Where(s => s.UserName == _cus.UserName && s.Password == _cus.Password).FirstOrDefault();
            if (check == null)  //không có KH
            {
                ViewBag.ErrorInfo = "Không có KH này";
                return View("LoginCus");
            }
            else
            {   // Có tồn tại KH -> chuẩn bị dữ liệu đưa về lại ShowCart.cshtml
                db.Configuration.ValidateOnSaveEnabled = false;
                Session["IDCus"] = check.IDCus;
                Session["Passwod"] = check.Password;
                Session["NameCus"] = check.NameCus;
                Session["PhoneCus"] = check.PhoneCus;
                // Quay lại trang giỏ hàng với thông tin cần thiết
                return RedirectToAction("ShowCart", "ShoppingCart");
            }
        }

    }
}

BanSach/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanSach.Models;
using PagedList;


namespace BanSach.Controllers
{
    public class ProductsController : Controller
    {
        private BanSachEntities db = new BanSachEntities();

        // GET: Products
        public ActionResult Index()
        {
            var product = db.Products.Include(p => p.Category1);
            return View(product.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
                return View(product);
            }
            catch
            {
                return Content("Vui lòng nhập tên sản phẩm không quá dài");
            }
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            Session["ImageSave"] = product.ImagePro;
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ImagePro == null)
                {
                    product.ImagePro = Session["ImageSave"].ToString();
                }
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // GET: Products
        public ActionResult ProductList(string SearchString, string category, int? page, double min = double.MinValue, double max = double.MaxValue)
        {
            var products = db.Products.Include(p => p.Category);
            // Tìm kiếm chuỗi truy vấn theo category
            if (category == null)
            {
                products = db.Products.OrderByDescending(x => x.NamePro);
            }
            else
            {
                products = db.Products.OrderByDescending(x => x.Category).Where(x => x.Category == category); // sửa CateID thành Category
            }
            // Tìm kiếm chuỗi truy vấn theo NamePro (SearchString)
            if (!String.IsNullOrEmpty(SearchString))
            {
                products = db.Products.OrderByDescending(x => x.NamePro).Where(x => x.NamePro.Contains(SearchString.Trim()));  //thêm OrderByDescending(x=>x.NamePro) sau db.Product.
            }
            // Tìm kiếm chuỗi truy vấn theo đơn giá
            if (min >= 0 && max > 0)
            {
                products = db.Products.OrderByDescending(x => x.Price).Where(p => (double)p.Price >= min && (double)p.Price <= max);
            }
            // Khai báo mỗi trang 4 sản phẩm
            int pageSize = 8;
            // Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // Nếu page = null thì đặt lại page là 1.
            if (page == null) page = 1;

            // Trả về các product được phân trang theo kích thước và số trang.
            return View(products.ToPagedList(pageNumber, pageSize));

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Infomation()
        {
            
            return View();
        }
    }
}

BanSach/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BanSach.Models;

namespace BanSach.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        BanSachEntities db = new BanSachEntities();
        // GET: ShoppingCart, chuẩn bị dữ liệu cho View
        public ActionResult ShowCart    ()
        {
            if (Session["Cart"] == null)
                return View("ShowCart");
            Cart _cart = Session["Cart"] as Cart;
            return View(_cart);
        }
        // Tạo mới giỏ hàng, nguồn được lấy từ Session
        public Cart GetCart()
        {
            Cart cart = Session["Cart"] as Cart;
            if (cart == null || Session["Cart"] == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
        // Thêm sản phẩm vào giỏ hàng
        public ActionResult AddToCart(int id)
        {
            // lấy sản phẩm theo id
            var _pro = db.Products.SingleOrDefault(s => s.ProductID == id);
            if (_pro != null)
            {
                GetCart().Add_Product_Cart(_pro);
            }
            return RedirectToAction("ShowCart", "ShoppingCart");
        }
        // Cập nhật số lượng và tính lại tổng tiền
        public ActionResult Update_Cart_Quantity(FormCollection form)
        {
            Cart cart = Session["Cart"] as Cart;
            int id_pro = int.Parse(Request.Form["idPro"]);
            int _quantity = int.Parse(Request.Form["carQuantity"]);
            cart.Update_quantity(id_pro, _quantity);

            return RedirectToAction("ShowCart", "ShoppingCart");
        }
        // Xóa dòng sản phẩm trong giỏ hàng
        public ActionResult RemoveCart(int id)
        {
            Cart cart = Session["Cart"] as Cart;
            cart.Remove_CartItem(id);
            return RedirectToAction("ShowCart", "ShoppingCart");
        }
        // Tính tổng tiền đơn hàng
        //public PartialViewResult BagCart()
        //{
        //    decimal total_money_item = 0;
        //    Cart cart = Session["Cart"] as Cart;
        //    if (cart != null)
        //        total_money_item = cart.Total_money();
        //    ViewBag.TotalCart = total_money_item;
        //    return PartialView("BagCart");
        //}

        public PartialViewResult BagCart()
        {
            int total_quantity_item = 0;
            Cart cart = Session["Cart"] as Cart;
            if (cart != null)
                total_quantity_item = cart.Total_quantity();
            ViewBag.QuantityCart = total_quantity_item;
            return PartialView("BagCart");
        }
        // Các phương thức cho thanh toán
        public ActionResult CheckOut(FormCollection form)
        {
            try
            {
                Cart cart = Session["Cart"] as Cart;
                OrderPro _order = new OrderPro();
                _order.DateOrder = DateTime.Now;
                _order.AddressDeliverry = form["AddressDeliverry"];
                _order.IDCus = int.Parse(form["CodeCustomer"]);
                db.OrderProes.Add(_order);
                foreach (var item in cart.Items)
                {
                    // lưu dòng sản phẩm vào chi tiết hóa đơn
                    OrderDetail _order_detail = new OrderDetail();
                    _order_detail.IDOrder = _order.ID;
                    _order_detail.IDProduct = item._product.ProductID;
                    _order_detail.UnitPrice = (double)item._product.Price;
                    _order_detail.Quantity = item._quantity;
                    db.OrderDetails.Add(_order_detail);
                }
                db.SaveChanges();
                cart.ClearCart();
                return RedirectToAction("CheckOut_Success", "ShoppingCart");
            }
            catch
            {
                return Content("Có sai sót! Xin kiểm tra lại thông tin"); ;
            }
        }
        // Thông báo thanh toán thành công
        public ActionResult CheckOut_Success()
        {
            return View();
        }

    }
}

BanSach/Views/ShoppingCart/BagCart.cshtml
<span style="color:; margin-left:" >
    @ViewBag.QuantityCart
</span>

BanSach/Views/ShoppingCart/CheckOut_Success.cshtml
@{
    ViewBag.Title = "CheckOut_Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thanh toán thành công</h2>
<h2>Hẹn gặp lại quí khách</h2>

BanSach/Views/ShoppingCart/ShowCart.cshtml
@model BanSach.Models.Cart

@{
    ViewBag.Title = "ShowCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model != null)
{
    <h2>Giỏ Hàng</h2>
    <a href="@Url.Action("ProductList", "Products")">Tiếp tục Mua hàng</a>

    @*<table class="table-bordered">
        <thead style="text-align:center; font-size:large;">
            <tr>
                <th>Tên Sản phẩm</th>
                <th>Hình</th>
                <th>Giá</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                decimal total = item._quantity * (decimal)item._product.Price.Value;
                <tr>
                    <td width="400">@Html.DisplayFor(model => item._product.NamePro)</td>
                    <td><img src="~/Content/images/@item._product.ImagePro" width="100" height="110" /></td>
                    <td width="100" align="right"> @Html.DisplayFor(model => item._product.Price)</td>
                    <td align="right">
                        @using (Html.BeginForm("Update_Cart_Quantity", "ShoppingCart"))
                        {
                            <input type="hidden" value="@item._product.ProductID" name="idPro" />
                            <input type="number" value="@item._quantity" name="carQuantity" style="text-align:right" />
                            <input type="submit" value="Cập nhật" />
                        }
                    </td>
                    <td width="100" align="right">@total.ToString("#,##0").Replace(',', '.')</td>
                    <td>
                        <a href="   RemoveCart/@item._product.ProductID" class="btn-danger">- Xóa -</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" align="center">
                    <br />
                    (Hãy đăng ký KH nếu chưa đăng ký)
                    <a href="@Url.Action("Create", "Customers")" class="btn btn-success">Đăng ký</a>
                </td>
                <td colspan="3" style="text-align:right; font-size:x-large; color: crimson;">
                    Tổng tiền : @Model.Total_money().ToString("#,##0").Replace(',', '.') Đồng
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <br />
                    <h4>-------------------THÔNG TIN ĐƠN HÀNG</h4>
                    @using (Html.BeginForm("CheckOut", "ShoppingCart"))
                    {
                        <table style="border-collapse:separate; border-spacing:5px;">
                            <tr>
                                <td></td>
                                <td><input type="hidden" name="CodeCustomer" value="@Session["IDCus"]" required /></td>
                            </tr>
                            <tr>
                                <td> Khách hàng : </td>
                                <td><input type="text" name="NameCustomer" value="@Session["NameCus"]" required /></td>
                            </tr>
                            <tr>
                                <td> Điên thoại : </td>
                                <td><input type="text" name="PhoneCustomer" value="@Session["PhoneCus"]" required /></td>
                            </tr>
                            <tr>
                                <td> Địa chỉ giao hàng : </td>
                                <td> <input type="text" name="AddressDeliverry" required /></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <a href="@Url.Action("LoginCus", "Customers")" class="btn btn-primary">Đăng nhập</a>
                                    (Hãy đăng nhập trước)
                                    <input type="submit" value="Thanh toán" class="btn btn-danger" />
                                </td>
                            </tr>
                        </table>
                    }
                </td>
                <td colspan="3"></td>
            </tr>
        </tfoot>
    </table>*@

    <section class="fill-cart">
        <div class="container my-5">
            <div class="row justify-content-center">
                @foreach (var item in Model.Items)
                {
                    decimal total = item._quantity * (decimal)item._product.Price.Value;
                    <div class="card mb-xl-3 me-3" style="max-width: 540px;">
                        <div class="row g-0">
                            <div class="col-4 col-sm-4 col-md-4">
                                <img src="~/Content/images/@item._product.ImagePro"
                                        class="img-fluid rounded-start" alt="...">
                            </div>
                            <div class="col-8 col-sm-8 col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">@Html.DisplayFor(model => item._product.NamePro)</h5>
                                    <div class="card-text">
                                        <p style="color:red; float:left; padding-top:5px;">@Html.DisplayFor(model => item._product.Price)</p>
                                        @using (Html.BeginForm("Update_Cart_Quantity", "ShoppingCart"))
                                        {
                                            <span style="float:right">
                                                <input type="hidden" value="@item._product.ProductID" name="idPro" />
                                                <input type="number" class="rounded-1" value="@item._quantity" name="carQuantity" style="text-align:right;width:40px;"  />
                                                <input type="submit" class="btn btn-primary rounded-pill" value="Cập nhật" />
                                            </span>
                                        }
                                    </div>
                                    <p class="card-text" style="clear:both;">
                                        <span class="fs-5" style="font-weight:600;float:left;">Tổng : @total.ToString("#,##0").Replace(',', '.') ₫</span>
                                        
                                        <a href="RemoveCart/@item._product.ProductID" class="btn btn-danger" style="float:right;">Xóa</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            
            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header fw-bold fs-4 text-center" >
                        --------------------- ĐƠN HÀNG ---------------------
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <span class="text-decoration-underline">Hãy đăng ký khách hàng nếu chưa đăng ký</span> ➩
                            <a href="@Url.Action("Create", "Customers")" class="btn btn-info">Đăng ký</a>
                        </h5>
                        <h5 class="card-title">
                            <span class="text-decoration-underline">Hãy đăng nhập nếu chưa đăng nhập</span> ➩
                            <a href="@Url.Action("LoginCus", "Customers")" class="btn btn-info">Đăng nhập</a>
                        </h5>
                        <h6 class="card-text fs-5 mb-3">Tổng tiền : @Model.Total_money().ToString("#,##0").Replace(',', '.') Đồng</h6>
                        @using (Html.BeginForm("CheckOut", "ShoppingCart"))
                        {
                            <input type="hidden" name="CodeCustomer" value="@Session["IDCus"]" required />
                            <p>
                                <text style="color:blue;padding-right:24px">Tên :</text>
                                <input type="text" name="NameCustomer" value="@Session["NameCus"]" required />
                            </p>
                            <p>
                                <text style="color:blue;padding-right:20px">SĐT :</text>
                                <input type="number" name="PhoneCustomer" value="@Session["PhoneCus"]" required />
                            </p>
                            <p>
                                <text style="color:blue;padding-right:px">Địa chỉ :</text>
                                <input type="text" name="AddressDeliverry" required />
                            </p>
                            <input type="submit" value="Thanh toán" class="btn btn-success fw-bold fs-5" style="width:150px;" />
                        }
                    </div>
                </div>
            </div>

        </div>
        </section>
}
else
{
    <section id="empty-cart">
        <div class="container my-5">
            <div class="row justify-content-center justify-content-md-center text-center">
                <div class="col-12">
                    <img class="img-fluid" src="~/Content/images/empty-cart.png" alt="empty-cart">
                    <div class="fw-bold fs-4">
                        Không tìm thấy sản phẩm nào trong giỏ hàng
                    </div>
                    <div>
                        <a href="@Url.Action("ProductList", "Products")">Quay lại mua hàng ...</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
}