BanSach/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BanSach.Models;

namespace BanSach.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Categories
        BanSachEntities database = new BanSachEntities();
        public ActionResult Index(string _name)
        {
            if(_name==null)
                return View(database.Categories.ToList());
            else
            return View(database.Categories.Where(s => s.NameCate.Contains(_name)).ToList());
        }


        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category cate)
        {
            try
            {
                database.Categories.Add(cate);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Error Create New");
            }
        }

        //Details
        public ActionResult Details(int id)
        {
            return View(database.Categories.Where(c => c.Id == id).FirstOrDefault());
        } 

        //Edit
        public ActionResult Edit(int id)
        {
            return View(database.Categories.Where(c => c.Id == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Edit(int id, Category cate)
        {
            try 
            {
                database.Entry(cate).State = System.Data.Entity.EntityState.Modified;
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Lỗi");
            }
        }
        
        //Delete
        public ActionResult Delete(int id)
        {
            return View(database.Categories.Where(c => c.Id == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Delete(int id, Category cate)
        {
            try
            {
                cate = database.Categories.Where(c => c.Id == id).FirstOrDefault();
                database.Categories.Remove(cate);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("This data is using in other table, Error Delete!");
            }
        }
        // Action PartialViewResult
        [ChildActionOnly]
        public PartialViewResult CategoryPartial()
        {
            var cateList = database.Categories.ToList();
            return PartialView(cateList);
        }

    }
}

BanSach/Controllers/LoginUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using BanSach;
using BanSach.Models;

namespace BanSach.Controllers
{
    public class LoginUserController : Controller
    {
        BanSachEntities database = new BanSachEntities();
        // GET: LoginUser
        // Phương thức tạo view cho Login
        public ActionResult Index()
        {
            return View();
        }
        // Xử lý tìm kiếm ID, password trong AdminUser và thông báo
        [HttpPost]
        public ActionResult LoginAcount(AdminUser _user)
        {
            Session["NameUser"] = null;
            var check = database.AdminUsers.Where(s => s.NameUser == _user.NameUser && s.PasswordUser == _user.PasswordUser).FirstOrDefault();
            if (check == null)
            {
                ViewBag.ErrorInfo = "Sai Info";
                return View("Index");
            }
            else
            {
                database.Configuration.ValidateOnSaveEnabled = false;
                Session["NameUser"] = _user.NameUser;
                Session["PasswodUser"] = _user.PasswordUser;
                return RedirectToAction("ProductList", "Products");
            }
        }


        //Register
        [HttpGet]
        public ActionResult RegisterUser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterUser(AdminUser _user)
        {
            if (ModelState.IsValid)
            {
              var check_ID = database.AdminUsers.Where(s => s.ID == _user.ID).FirstOrDefault();
                if (check_ID == null)
                {
                    database.Configuration.ValidateOnSaveEnabled = false;
                    database.AdminUsers.Add(_user);
                    database.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorRegister = "ID này đã có rồi !!!";
                    return View();
                }
            }
            return View();        
        }
        public ActionResult LogOutUser()
        {
            Session.Abandon();
            return RedirectToAction("ProductList", "Products");
        }

    }
}

BanSach/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanSach.Models;
using PagedList;


namespace BanSach.Controllers
{
    public class ProductsController : Controller
    {
        private BanSachEntities db = new BanSachEntities();

        // GET: Products
        public ActionResult Index()
        {
            var product = db.Products.Include(p => p.Category1);
            return View(product.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
                return View(product);
            }
            catch
            {
                return Content("Vui lòng nhập tên sản phẩm không quá dài");
            }
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            Session["ImageSave"] = product.ImagePro;
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ImagePro == null)
                {
                    product.ImagePro = Session["ImageSave"].ToString();
                }
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // GET: Products
        public ActionResult ProductList(string SearchString, string category, int? page, double min = double.MinValue, double max = double.MaxValue)
        {
            var products = db.Products.Include(p => p.Category);
            // Tìm kiếm chuỗi truy vấn theo category
            if (category == null)
            {
                products = db.Products.OrderByDescending(x => x.NamePro);
            }
            else
            {
                products = db.Products.OrderByDescending(x => x.Category).Where(x => x.Category == category); // sửa CateID thành Category
            }
            // Tìm kiếm chuỗi truy vấn theo NamePro (SearchString)
            if (!String.IsNullOrEmpty(SearchString))
            {
                products = db.Products.OrderByDescending(x => x.NamePro).Where(x => x.NamePro.Contains(SearchString.Trim()));  //thêm OrderByDescending(x=>x.NamePro) sau db.Product.
            }
            // Tìm kiếm chuỗi truy vấn theo đơn giá
            if (min >= 0 && max > 0)
            {
                products = db.Products.OrderByDescending(x => x.Price).Where(p => (double)p.Price >= min && (double)p.Price <= max);
            }
            // Khai báo mỗi trang 4 sản phẩm
            int pageSize = 8;
            // Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // Nếu page = null thì đặt lại page là 1.
            if (page == null) page = 1;

            // Trả về các product được phân trang theo kích thước và số trang.
            return View(products.ToPagedList(pageNumber, pageSize));

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Infomation()
        {
            
            return View();
        }
    }
}

BanSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web Bán sách</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="~/CSS/Bán-sách-BST.css" type="text/css" rel="stylesheet">
    <link rel="stylesheet" href="~/CSS/mycss.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://fonts.google.com/specimen/Roboto">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>

    <!--navbar-->
    <nav class="navbar navbar-expand-md bg-info">
        <div class="container">
            <div class="row justify-content-md-center justify-content-md-start">
                <div class="col-7 col-sm-7 col-md-6 col-lg-2 mb-1
            align-self-md-center">
                    <a class="navbar-brand"
                       href="@Url.Action("ProductList", "Products")">
                        <img class="img-fluid" src="~/Content/images/logo-sách2.png"
                             alt="logo web">
                    </a>
                </div>
                <!-- Force next columns to break to new line at md breakpoint and up -->
                <div class="w-100 d-none d-md-block d-lg-none"></div>

                <div class="col-md-5 col-lg-3 align-self-md-center">
                    <form class="d-flex d-xl-flex mb-1 mt-2">
                        <input class="form-control me-1 rounded-pill" type="search" placeholder="Tên sách..." aria-label="Search" name="SearchString">
                        <button class="btn rounded-pill btn-success" type="submit">
                            <span class="bi-search"></span>
                        </button>
                    </form>
                </div>
                <div class="col-md-7 col-lg-7 align-self-md-center">
                    <!--Toggle button for mobile devices-->
                    <button class="navbar-toggler" type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle
              navigation">
                        <span class="bi-list-ul"></span>
                    </button>

                    <!--navbar links-->
                    <div class="collapse navbar-collapse"
                         id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-lg-0 fw-semibold">
                            <li class="nav-item">
                                <a class="nav-link active bi-house-fill
                    me-2" aria-current="page" href="@Url.Action("ProductList", "Products")">
                                    Trang
                                    chủ
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-2 bi-info-circle-fill"
                                   href="@Url.Action("Infomation", "Products")">Thông tin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-2 bi-telephone-fill"
                                   href="#">Liên hệ</a>
                            </li>
                            <li class="nav-item dropdown account">
                                <a class="nav-link dropdown-toggle me-2
                    bi-person-circle" href="#"
                                   id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    Tài khoản
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item" href="/LoginUser/Index">
                                            Đăng
                                            nhập
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="/LoginUser/RegisterUser">
                                            Phân quyền
                                        </a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a class="dropdown-item" href="@Url.Action("LogOutUser", "LoginUser")">
                                            Đăng xuất
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-2 bi-cart4" href="/ShoppingCart/ShowCart">
                                    Giỏ hàng
                                </a>
                            </li>
                            <li style="padding-top:8px;">
                                @if (Session["NameUser"] == null)
                                {
                                    <span>Chào mừng</span>
                                }
                                else
                                {
                                    <span class="bi-person-circle"> @Session["NameUser"]</span>
                                }
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    @{Html.RenderAction("CategoryPartial", "Categories");}
    <div class="container ">
        @RenderBody()
    </div>
        <footer class="footer">
            <div class="container">
                <!--Bắt Đầu Nội Dung Giới Thiệu-->
                <div class="noi-dung about">
                    <h2>Về Chúng Tôi</h2>
                    <p>IMBM HỒ CHÍ MINH - ĐẠI LÝ PHÂN PHỐI SÁCH CHÍNH HÃNG TẠI TP.HCM</p>
                    <p>GIẤY CNĐKDN: 0600252847-008 NGÀY CẤP 29/02/2012</p>
                    <ul class="social-icon">
                        <li><a href="https://www.facebook.com/trunghung03/"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.instagram.com/chun_huwq/"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="https://www.youtube.com/channel/UCYXYSkPd4U6hvsCxztmynEQ"><i class="fa fa-youtube"></i></a></li>
                    </ul>
                </div>
                <!--Kết Thúc Nội Dung Giới Thiệu-->
                <!--Bắt Đầu Nội Dung Đường Dẫn-->
                <div class="noi-dung links">
                    <h2>Đường Dẫn</h2>
                    <ul>
                        <li><a href="#">Chính sách và Điều khoản</a></li>
                        <li><a href="#">Chính sách bảo mật thông tin</a></li>
                    </ul>
                </div>
                <!--Kết Thúc Nội Dung Đường Dẫn-->
                <!--Bắt Đâu Nội Dung Liên Hệ-->
                <div class="noi-dung contact">
                    <h2>Thông Tin Liên Hệ</h2>
                    <ul class="info">
                        <li>
                            <span><i class="fa fa-map-marker"></i></span>
                            <span style="color:black">
                                828 Sư Vạn Hạnh, Phường 12<br />
                                Quận 10, Thành phố Hồ Chí Minh<br />
                                Việt Nam
                            </span>
                        </li>
                        <li>
                            <span><i class="fa fa-phone"></i></span>
                            <p>
                                <a style="color:black" href="tel://0396087917">0396087917</a>
                                <br />
                                <a style="color:black" href="tel://0906936355">0906936355</a>
                            </p>
                        </li>
                        <li>
                            <span><i class="fa fa-envelope"></i></span>
                            <p><a style="color:black" href="mailto:trunghungpq456@gmail.com">IMBM@gmail.com</a></p>
                        </li>
                        
                    </ul>
                </div>
                <!--Kết Thúc Nội Dung Liên Hệ-->
            </div>
            <div class="row" >
                <a style="text-align:right">
                    Copyright 2022 © Nhà sách TP Hồ Chí Minh
                </a>
                
            </div>
        </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>
    <script src="Bán-sách-BST.js" type="text/javascript"></script>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>